CONFIG = b""
PIN_ALARMA = 17
PIN_STOP_ALARMA = 4
SET_TEMP = 0
SET_HUM = 80
LIST_SENSOR = {"SENSOR_1": "SENSOR_1", "SENSOR_2": "SENSOR_2"}
BROKER = {"DEVICE": "ORANGE_PI", "ADRESS": "192.168.0.16",
          "NAME": "FrosTool", "PASSWORD": "Password_de_paso"}
CULTIVO = {"TIPO_CULTIVO": "UVAS", "LOCATION": "5.7180354, -72.9244577"}
SENSOR_1 = {"REFERENCIA": "MQ-2",
            "TOPIC_1": "/CULTIVO/SENSOR_1/TEMP",
            "TOPIC_2": "/CULTIVO/SENSOR_1/HUM", "VARIABLE_1": "TEMPERATURA",
            "VARIABLE_2": "HUMEDA",}
SENSOR_2 = {"REFERENCIA": "MQ-2",
            "TOPIC": "/CULTIVO/SENSOR_1/TEMP", "VARIABLE": "TEMPERATURA", }


SENSOR_1 = {"REFERENCIA": "DHT22", "ID": "UnidID", "TYPE1": "TEMPERATURA", "TYPE2": "HUMEDAD", "TYPE3": "None"}
TOPICOS = {"TEMPERATURA": b"/CULTIVO/TEMP", "HUMEDAD": b"/CULTIVO/HUM", "ALARMA": b"/CULTIVO/ALARMA"}
